probe for the existence of DONE in tests

diff --git a/test/nrginit+nrgrun_long/runtest b/test/nrginit+nrgrun_long/runtest
--- a/test/nrginit+nrgrun_long/runtest
+++ b/test/nrginit+nrgrun_long/runtest
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -o pipefail
 # $1 = $PROJECT_SOURCE_DIR
 # $2 = $PROJECT_BINARY_DIR
 # $3 = $CMAKE_CURRENT_SOURCE_DIR/${test}
@@ -7,6 +8,10 @@
 "$2/c++/nrg" 2>&1 | tee log
 if [ $? -ne 0 ]; then
   echo "Abnormal termination. Skipping comparisons."
+  exit 1
+fi
+if [ ! -f "DONE" ]; then
+  echo "File DONE not found. Skipping comparisons."
   exit 1
 fi
 "$1/test/compare.pl" "$3/ref"
